version: '3'


services:
  test_app:
    build:
      context: .
      dockerfile: ./build/app_test.Dockerfile
    depends_on:
      - test_db
    networks:
      - postgres
    environment:
      - POSTGRES_TEST_USER
      - POSTGRES_TEST_DB
      - POSTGRES_TEST_PASSWORD

  test_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER:?}
      - POSTGRES_DB=${POSTGRES_TEST_DB:?}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD:?}
    networks:
      - postgres


networks:
  postgres:
    driver: bridge
