version: '3'


services:
  test_app:
    build:
      context: .
      dockerfile: ./build/app_test.Dockerfile
    networks:
      - postgres
    environment:
      - POSTGRES_TEST_USER
      - POSTGRES_TEST_DB
      - POSTGRES_TEST_PASSWORD

  test_db:
    image: postgres
    restart: always
    volumes:
      - ./data/test_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER:?}
      - POSTGRES_DB=${POSTGRES_TEST_DB:?}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD:?}
    networks:
      - postgres
      
networks:
  postgres:
    driver: bridge
