version: '3'


services:
  app:
    build:
      context: .
      dockerfile: ./build/app.Dockerfile
    restart: unless-stopped
    networks:
      - app-network
    ports:
    - "8080:8080"

networks:
  app-network:
    driver: bridge
