version: '3'


services:
  app:
    build:
      context: .
      dockerfile: ./build/app.Dockerfile
    restart: unless-stopped
    networks:
      - app-network
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - CAPTCHA_SITE_KEY
      - CAPTCHA_SECRET_KEY
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
    - 5432:5432
    networks:
      - postgres

  adminer:
    image: adminer
    restart: always
    networks:
      - postgres
    ports:
      - 9000:9000

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./conf/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    command: "nginx -g 'daemon off;'"
    networks:
    - app-network

networks:
  postgres:
    driver: bridge
  app-network:
    driver: bridge
